version: '3.8'

networks:
  mongo_6:
    name: mongo_6
    driver: overlay
    attachable: true

volumes:
  mongo_6:
    driver: local

services:
  mongo_6:
    image: mongo:6.0.4
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.service == mongo
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '8'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 1G    
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_6:/data/db/
    ports:
      - 27217:27017
      - 27218:27018
      - 27219:27019
    networks:
      - mongo_6
    command: --wiredTigerCacheSizeGB=2 --dbpath /data/db