version: "3.9"

networks:
  mongo_next:
    name: mongo_next
    driver: overlay
    attachable: true

volumes:
  mongo_next:
    driver: local

services:
  mongo_next:
    image: mongo:6.0.5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: "4"
          memory: 2G
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_next:/data/db/
    ports:
      - 27117:27017
      - 27118:27018
      - 27119:27019
    networks:
      - mongo_next
    command: --wiredTigerCacheSizeGB=1 --dbpath /data/db
