version: '3.8'

networks:
  mongo_next:
    name: mongo_next
    driver: overlay
    attachable: true

volumes:
  mongo_next:
    driver: local

services:
  mongo_next:
    image: mongo:5.0.3
    deploy:
      replicas: 1
      restart_policy:
        condition: 'any'
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 500M    
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_next:/data/db/
    ports:
      - 27117:27017
      - 27118:27018
      - 27119:27019
    networks:
      - mongo_next
    command: --wiredTigerCacheSizeGB=1 --dbpath /data/db