name: deployment@5

on:
  push:
    branches:
      - 5

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 5

      - name: (SCP) Copy Docker files to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_SSH_PORT }}
          source: "src/5/docker-compose.yml"
          target: "deploy"

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_SSH_PORT }}
          script: |
            echo "MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}" > /home/runner/deploy/src/5/docker-compose.env
            echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> /home/runner/deploy/src/5/docker-compose.env
            echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> /home/runner/deploy/src/5/docker-compose.env
            sudo /opt/deploy-docker-stack.sh /home/runner/deploy/src/5/docker-compose.yml /home/runner/deploy/src/5/docker-compose.env mongo_5